export const PROVIDER_CAPABILITIES = [
  "AUTHENTICATION",
  "IDENTITY_LIFECYCLE",
  "GROUP_DISCOVERY",
  "RESOURCE_DISCOVERY",
  "ACCESS_PROVISIONING",
  "INCREMENTAL_SYNC",
  "OFFLINE_OPERATION",
] as const;

export type ProviderCapability = (typeof PROVIDER_CAPABILITIES)[number];
